In [264]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd

In [265]:
data_set = pd.read_excel('Covid_Data_new.xlsx')
X = data_set.iloc[:, :-1].values
Y = data_set.iloc[:, -1].values

In [266]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [nan 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]
 [35.0 'Modera

In [267]:
print(Y)

['No' 'No' 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'No' 'No'
 'No' 'No' 'No' 'Yes' 'No' 'No' 'No' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes'
 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes'
 'Yes' 'No' 'Yes' 'Yes' 'Yes']


In [268]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer.fit(X[:,0:1])
X[:,0:1] = imputer.transform(X[:,0:1])

In [269]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' nan]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' 'no' 'no' 89.0]

In [270]:
imputer.fit(X[:,4:5])
X[:,4:5] = imputer.transform(X[:,4:5])

In [271]:
print(X)

[[10.0 'Normal' 'no' 'no' 97.0]
 [12.0 'Normal' 'no' 'no' 97.0]
 [15.0 'Normal' 'no' 'no' 94.0]
 [10.0 'Normal' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 94.0]
 [12.0 'Moderate' 'no' 'no' 97.0]
 [13.0 'Moderate' 'no' 'no' 93.0]
 [15.0 'Moderate' 'no' 'no' 92.0]
 [18.0 'Moderate' 'no' 'no' 66.0]
 [19.0 'Normal' 'no' 'no' 92.0]
 [20.0 'Normal' 'no' 'no' 93.0]
 [17.0 'Normal' 'no' 'no' 93.0]
 [16.0 'Normal' 'no' 'no' 92.0]
 [18.0 'Normal' 'no' 'no' 93.0]
 [20.0 'Normal' 'no' 'no' 92.0]
 [25.0 'Moderate' 'no' 'no' 93.0]
 [24.0 'Moderate' 'no' 'no' 92.0]
 [26.0 'High' 'no' 'no' 94.0]
 [28.0 'Normal' 'no' 'no' 99.0]
 [29.0 'Normal' 'no' 'no' 93.0]
 [30.0 'Moderate' 'no' 'no' 62.0]
 [19.0 'Normal' 'no' 'no' 89.0]
 [25.0 'Normal' 'no' 'yes' 86.0]
 [26.0 'Normal' 'no' 'no' 82.07246376811594]
 [28.0 'Normal' 'no' 'no' 89.0]
 [30.0 'Moderate' 'yes' 'no' 86.0]
 [35.0 'Moderate' 'no' 'no' 89.0]
 [32.0 'Moderate' 'no' 'yes' 84.0]
 [45.130434782608695 'Moderate' 'yes' 'no' 90.0]
 [32.0 'Moderate' '

In [272]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [273]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [274]:
print(X)

[[0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 12.0 'no' 'no' 97.0]
 [0.0 0.0 1.0 15.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 10.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 94.0]
 [0.0 1.0 0.0 12.0 'no' 'no' 97.0]
 [0.0 1.0 0.0 13.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 15.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 18.0 'no' 'no' 66.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 17.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 16.0 'no' 'no' 92.0]
 [0.0 0.0 1.0 18.0 'no' 'no' 93.0]
 [0.0 0.0 1.0 20.0 'no' 'no' 92.0]
 [0.0 1.0 0.0 25.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 24.0 'no' 'no' 92.0]
 [1.0 0.0 0.0 26.0 'no' 'no' 94.0]
 [0.0 0.0 1.0 28.0 'no' 'no' 99.0]
 [0.0 0.0 1.0 29.0 'no' 'no' 93.0]
 [0.0 1.0 0.0 30.0 'no' 'no' 62.0]
 [0.0 0.0 1.0 19.0 'no' 'no' 89.0]
 [0.0 0.0 1.0 25.0 'no' 'yes' 86.0]
 [0.0 0.0 1.0 26.0 'no' 'no' 82.07246376811594]
 [0.0 0.0 1.0 28.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 30.0 'yes' 'no' 86.0]
 [0.0 1.0 0.0 35.0 'no' 'no' 89.0]
 [0.0 1.0 0.0 32.0 'no' 'yes' 84.0]
 [0.

In [275]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[5])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [276]:
print(X)

[[1.0 0.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 0.0 1.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 0.0 1.0 15.0 'no' 94.0]
 [1.0 0.0 0.0 0.0 1.0 10.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 0.0 13.0 'no' 94.0]
 [1.0 0.0 0.0 1.0 0.0 12.0 'no' 97.0]
 [1.0 0.0 0.0 1.0 0.0 13.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 15.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 0.0 18.0 'no' 66.0]
 [1.0 0.0 0.0 0.0 1.0 19.0 'no' 92.0]
 [1.0 0.0 0.0 0.0 1.0 20.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 17.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 16.0 'no' 92.0]
 [1.0 0.0 0.0 0.0 1.0 18.0 'no' 93.0]
 [1.0 0.0 0.0 0.0 1.0 20.0 'no' 92.0]
 [1.0 0.0 0.0 1.0 0.0 25.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 24.0 'no' 92.0]
 [1.0 0.0 1.0 0.0 0.0 26.0 'no' 94.0]
 [1.0 0.0 0.0 0.0 1.0 28.0 'no' 99.0]
 [1.0 0.0 0.0 0.0 1.0 29.0 'no' 93.0]
 [1.0 0.0 0.0 1.0 0.0 30.0 'no' 62.0]
 [1.0 0.0 0.0 0.0 1.0 19.0 'no' 89.0]
 [0.0 1.0 0.0 0.0 1.0 25.0 'no' 86.0]
 [1.0 0.0 0.0 0.0 1.0 26.0 'no' 82.07246376811594]
 [1.0 0.0 0.0 0.0 1.0 28.0 'no' 89.0]
 [1.0 0.0 0.0 1.0 0.0 30.0 'yes' 86.0

In [277]:
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[6])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))

In [278]:
print(X)

[[1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 15.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 12.0 97.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 15.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 18.0 66.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 17.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 18.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 92.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 25.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 26.0 94.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 93.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 30.0 62.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 89.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 26.0 82.07246376811594]
 [1

In [279]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [280]:
print(Y)

[0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 0 1 1 1]


In [281]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [282]:
print(X_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 0.0 86.0 71.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 35.0 92.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 75.0 72.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 42.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 74.0 75.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 62.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 24.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 48.0 93.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 58.0 70.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 45.130434782608695 90.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 15.0 92.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 70.0 88.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 52.0 80.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 60.0 68.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 54.0 70.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 93.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 78.0 71.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 36.0 90.0]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 30.0 86.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 50.0 77.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 18.0 93.0]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 69.0 53.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 26.0 94.0]
 [

In [283]:
print(Y_train)

[1 0 1 0 1 1 0 0 1 0 0 0 1 1 1 0 1 0 0 1 0 1 0 0 1 1 0 0 1 1 1 0 0 1 0 1 0
 1 1 0 0 0 1 1 0 1 1 0 1 0 0 0 1 0 0 1]


In [284]:
print(X_test)

[[1.0 0.0 0.0 1.0 0.0 0.0 1.0 25.0 86.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 97.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 68.0 67.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 94.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 59.0 68.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 28.0 99.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 93.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 46.0 91.0]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 53.0 55.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16.0 92.0]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 38.0 75.0]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 92.0]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 94.0 64.0]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 12.0 97.0]]


In [285]:
print(Y_test)

[0 0 1 0 1 0 0 0 1 0 1 0 1 0]


In [286]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)

X_train shape: (56, 9)
X_test shape: (14, 9)


In [287]:
from sklearn.preprocessing import StandardScaler

# Instantiate StandardScaler
sc = StandardScaler()

# Fit and transform the training set
X_train[:, 8:] = sc.fit_transform(X_train[:, 8:])

# Transform X_test using the same scaler fitted to X_train
X_test[:, 8:] = sc.transform(X_test[:, 8:])


In [288]:
print(X_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 0.0 86.0 -0.9941858494300261]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 35.0 0.9574354145081887]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 75.0 -0.9012515035282064]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 42.0 0.9574354145081887]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 74.0 -0.6224484658227472]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 62.0 -1.2729888871354853]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 24.0 0.9574354145081887]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 48.0 1.0503697604100084]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 58.0 -1.087120195331846]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 45.130434782608695 0.7715667227045492]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 15.0 0.9574354145081887]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 70.0 0.5856980309009097]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 52.0 -0.15777673631364833]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 60.0 -1.2729888871354853]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 54.0 -1.087120195331846]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 1.0503697604100084]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 78.0 -0.9941858494300261]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 36.0 0.771566

In [289]:
print(X_test)

[[1.0 0.0 0.0 1.0 0.0 0.0 1.0 25.0 0.3998293390972702]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 10.0 1.4221071440172874]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 68.0 -1.3659232330373052]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 13.0 1.143304106311828]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 59.0 -1.2729888871354853]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 28.0 1.607975835820927]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 20.0 1.0503697604100084]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 46.0 0.864501068606369]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 53.0 -2.4811353838591423]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 16.0 0.9574354145081887]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 38.0 -0.6224484658227472]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 19.0 0.9574354145081887]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 94.0 -1.6447262707427643]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 12.0 1.4221071440172874]]


In [293]:
X_train[:, 7:8] = sc.fit_transform(X_train[:, 7:8])

# Transform X_test using the same scaler fitted to X_train
X_test[:, 7:8] = sc.transform(X_test[:, 7:8])

In [294]:
print(X_train)

[[0.0 1.0 0.0 1.0 1.0 0.0 0.0 1.660595032652111 -0.9941858494300262]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 -0.5372483818439074 0.9574354145081888]
 [1.0 0.0 0.0 1.0 1.0 0.0 0.0 1.1865503746235582 -0.9012515035282065]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 -0.23558359946210095 0.9574354145081888]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 1.1434554057118715 -0.6224484658227473]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.6263157787716318 -1.2729888871354855]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 -1.0112930398724604 0.9574354145081888]
 [1.0 0.0 0.0 1.0 0.0 1.0 0.0 0.022986214008018892 1.0503697604100086]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.4539359031248853 -1.0871201953318461]
 [0.0 1.0 1.0 0.0 0.0 1.0 0.0 -0.10067760982551668 0.7715667227045493]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 -1.39914776007764 0.9574354145081888]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.9710755300651249 0.5856980309009098]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.19536608965476546 -0.1577767363136484]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 0.5401258409482586 -1.2729888871354855]
 [0.0 1.0 0.0 1.0 1.

In [295]:
print(X_test)

[[1.0 0.0 0.0 1.0 0.0 0.0 1.0 -0.9681980709607738 0.3998293390972702]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -1.6146226046360734 1.4221071440172877]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.8848855922417517 -1.3659232330373055]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 -1.4853376979010133 1.1433041063118283]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.4970308720365719 -1.2729888871354855]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -0.8389131642257138 1.6079758358209273]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -1.183672915519207 1.0503697604100086]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 -0.06320372381535438 0.8645010686063691]
 [0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.23846105856645208 -2.481135383859143]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -1.3560527911659535 0.9574354145081888]
 [1.0 0.0 1.0 0.0 1.0 0.0 0.0 -0.4079634751088475 -0.6224484658227473]
 [1.0 0.0 1.0 0.0 0.0 0.0 1.0 -1.2267678844308936 0.9574354145081888]
 [0.0 1.0 0.0 1.0 1.0 0.0 0.0 2.005354783945604 -1.6447262707427646]
 [1.0 0.0 1.0 0.0 0.0 1.0 0.0 -1.5284326668127002 1.4221071440172877]]
